
baseclass = {'pj': '',
     'titre': '',
     'al': '',
     'niv': '',
     'pv': '',
     'pvmax': '',
     'init': '',
     'mvren': '',
     'mvext': '',
     'mvvoy': '',
     'ca': '',
     'canu': '',
     'bonusatt': '',
     'bonusdist': '',
     'for': '',
     'int': '',
     'sag': '',
     'dex': '',
     'con': '',
     'cha': '',
     'forb': '',
     'intb': '',
     'sagb': '',
     'dexb': '',
     'conb': '',
     'chab': '',
     'xp': '0',
     'pp': '',
     'po': '',
     'pe': '',
     'pa': '',
     'pc': ''}

clecric = {
     'classe': 'Clerc',
     'dv': 'd6',
     'facultes': '',
     'svmort': '11',
     'savbag': '12',
     'svpara': '14',
     'svsouf': '16',
     'svsort': '15',
     'xpsuiv': '1500',
     'xpbonus': '',
     'equip1': '',
     'equip2': ''}

dwarf = {
     'classe': 'Nain',
     'dv': 'd8',
     'facultes': '',
     'svmort': '8',
     'savbag': '9',
     'svpara': '10',
     'svsouf': '13',
     'svsort': '12',
     'xpsuiv': '2200',
     'xpbonus': '',
     'equip1': '',
     'equip2': ''}
